### ISSUE TITLE
Pressing Ctrl+C dumps the stack to the screen

### ISSUE THREAD

**Issue by hoop33** [Availity/availity-cli#28]
hitting cancel while running availity init

>availity init
Enter a description for your application: /Users/rmcguinness/Dev/homebrew/lib/node_modules/availity-cli/lib/availity.project.js:207
  parameters['name'] = name === '.' ? currentDirectoryName() : name;
                                                               ^
TypeError: Cannot set property 'name' of undefined
    at Object.exports.initApplication (/Users/rmcguinness/Dev/homebrew/lib/node_modules/availity-cli/lib/availity.project.js:207:64)
    at /Users/rmcguinness/Dev/homebrew/lib/node_modules/availity-cli/lib/availity.project.js:372:13
    at /Users/rmcguinness/Dev/homebrew/lib/node_modules/availity-cli/node_modules/prompt/lib/prompt.js:316:20
    at /Users/rmcguinness/Dev/homebrew/lib/node_modules/availity-cli/node_modules/prompt/node_modules/utile/node_modules/async/lib/async.js:136:21
    at assembler (/Users/rmcguinness/Dev/homebrew/lib/node_modules/availity-cli/node_modules/prompt/lib/prompt.js:282:18)
    at /Users/rmcguinness/Dev/homebrew/lib/node_modules/availity-cli/node_modules/prompt/lib/prompt.js:322:20
    at /Users/rmcguinness/Dev/homebrew/lib/node_modules/availity-cli/node_modules/prompt/lib/prompt.js:510:14
    at onError (/Users/rmcguinness/Dev/homebrew/lib/node_modules/availity-cli/node_modules/prompt/node_modules/read/lib/read.js:94:12)
    at Interface.<anonymous> (/Users/rmcguinness/Dev/homebrew/lib/node_modules/availity-cli/node_modules/prompt/node_modules/read/lib/read.js:66:5)
    at Interface.emit (events.js:104:17)
    at Interface._ttyWrite (readline.js:694:16)
    at ReadStream.onkeypress (readline.js:109:10)
    at ReadStream.emit (events.js:110:17)
    at readline.js:1175:14
    at Array.forEach (native)
    at emitKeys (readline.js:993:10)
    at ReadStream.onData (readline.js:910:14)
    at ReadStream.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at ReadStream.Readable.push (_stream_readable.js:126:10)
    at TTY.onread (net.js:529:20)

**Comment by hoop33** [comment]
https://thomashunter.name/blog/gracefully-kill-node-js-app-from-ctrl-c/

**Comment by hoop33** [comment]
http://stackoverflow.com/questions/14031763/doing-a-cleanup-action-just-before-node-js-exits
